services:
  ipfs_host:
    image: ipfs/kubo:latest
    container_name: ipfs_kubo
    environment:
      - IPFS_PROFILE=server
    volumes:
      - $ipfs_staging:/export
      - $ipfs_data:/data/ipfs
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:5001:5001"
    # command: [ "daemon", "--offline" ] #offline mode
    restart: unless-stopped